2021-05-09 10:44:19,217 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting env: {}
2021-05-09 10:44:19,217 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-09 10:44:19,217 INFO    MainThread:14540 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_104419-344fg17p\logs\debug.log
2021-05-09 10:44:19,218 INFO    MainThread:14540 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_104419-344fg17p\logs\debug-internal.log
2021-05-09 10:44:19,218 INFO    MainThread:14540 [wandb_init.py:init():369] calling init triggers
2021-05-09 10:44:19,220 INFO    MainThread:14540 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'epochs': 600, 'learningRate': 0.0001, 'batchSize': 128, 'inputSize': 256, 'fc_size_1': 256, 'fc_size_2': 128, 'fc_size_3': 64, 'fc_size_4': 32, 'fc_size_5': 16, 'fc_size_6': 8, 'outputSize': 4, 'classes': ['COVID', 'Lung Opacity', 'Normal', 'Viral Pneumonia'], 'classesLen': 4, 'upSampling': True}
2021-05-09 10:44:19,220 INFO    MainThread:14540 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 5rtpwi6c
2021-05-09 10:44:19,222 INFO    MainThread:14540 [wandb_run.py:finish():1197] finishing run tecai/MLP/5rtpwi6c
2021-05-09 10:44:19,224 ERROR   MainThread:14540 [jupyter.py:save_history():312] Run pip install nbformat to save notebook history
2021-05-09 10:44:19,224 INFO    MainThread:14540 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-09 10:44:19,224 INFO    MainThread:14540 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-09 10:44:19,224 INFO    MainThread:14540 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 0
2021-05-09 10:44:19,225 INFO    MainThread:14540 [wandb_run.py:_restore():1496] restore
2021-05-09 10:44:19,539 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1099
  total_bytes: 1099
}

2021-05-09 10:44:19,974 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1099
  total_bytes: 3429
}

2021-05-09 10:44:20,239 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1099
  total_bytes: 3429
}

2021-05-09 10:44:20,347 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1099
  total_bytes: 3429
}

2021-05-09 10:44:20,455 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2451
  total_bytes: 3429
}

2021-05-09 10:44:20,564 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3429
  total_bytes: 3429
}

2021-05-09 10:44:20,674 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3429
  total_bytes: 3429
}

2021-05-09 10:44:20,783 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3429
  total_bytes: 3429
}

2021-05-09 10:44:20,892 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3429
  total_bytes: 3429
}

2021-05-09 10:44:21,004 INFO    MainThread:14540 [wandb_run.py:_wait_for_finish():1646] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3429
  total_bytes: 3429
}

2021-05-09 10:44:22,172 INFO    MainThread:14540 [wandb_run.py:_show_files():1868] logging synced files
2021-05-09 10:44:22,190 INFO    MainThread:14540 [wandb_init.py:init():418] starting backend
2021-05-09 10:44:22,191 INFO    MainThread:14540 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2021-05-09 10:44:22,197 INFO    MainThread:14540 [backend.py:ensure_launched():123] starting backend process...
2021-05-09 10:44:22,350 INFO    MainThread:14540 [backend.py:ensure_launched():127] started backend process with pid: 12916
2021-05-09 10:44:22,351 INFO    MainThread:14540 [wandb_init.py:init():423] backend started and connected
2021-05-09 10:44:22,356 INFO    MainThread:14540 [wandb_init.py:init():465] updated telemetry
2021-05-09 10:44:22,357 INFO    MainThread:14540 [wandb_init.py:init():484] communicating current version
2021-05-09 10:44:24,551 INFO    MainThread:14540 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-09 10:44:24,552 INFO    MainThread:14540 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-09 10:44:24,987 INFO    MainThread:14540 [wandb_init.py:init():522] starting run threads in backend
2021-05-09 10:44:26,075 INFO    MainThread:14540 [wandb_run.py:_console_start():1554] atexit reg
2021-05-09 10:44:26,076 INFO    MainThread:14540 [wandb_run.py:_redirect():1401] redirect: SettingsConsole.WRAP
2021-05-09 10:44:26,077 INFO    MainThread:14540 [wandb_run.py:_redirect():1444] Wrapping output streams.
2021-05-09 10:44:26,077 INFO    MainThread:14540 [wandb_run.py:_redirect():1468] Redirects installed.
2021-05-09 10:44:26,077 INFO    MainThread:14540 [wandb_init.py:init():546] run started, returning control to user process
2021-05-09 10:44:26,077 INFO    MainThread:14540 [wandb_watch.py:watch():39] Watching
2021-05-09 10:47:00,814 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting env: {}
2021-05-09 10:47:00,814 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-09 10:47:00,815 INFO    MainThread:14540 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_104700-1mtbzctc\logs\debug.log
2021-05-09 10:47:00,815 INFO    MainThread:14540 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_104700-1mtbzctc\logs\debug-internal.log
2021-05-09 10:47:00,815 INFO    MainThread:14540 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000027BEB992F10>
2021-05-09 10:47:00,818 INFO    MainThread:14540 [wandb_init.py:init():369] calling init triggers
2021-05-09 10:47:00,818 INFO    MainThread:14540 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'epochs': 600, 'learningRate': 0.0001, 'batchSize': 128, 'inputSize': 256, 'fc_size_1': 256, 'fc_size_2': 128, 'fc_size_3': 64, 'fc_size_4': 32, 'fc_size_5': 16, 'fc_size_6': 8, 'outputSize': 4, 'classes': ['COVID', 'Lung Opacity', 'Normal', 'Viral Pneumonia'], 'classesLen': 4, 'upSampling': True}
2021-05-09 10:47:00,818 INFO    MainThread:14540 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 344fg17p
2021-05-09 10:47:00,820 INFO    MainThread:14540 [wandb_run.py:finish():1197] finishing run tecai/MLP/344fg17p
