2021-05-10 14:01:30,985 INFO    MainThread:7276 [wandb_setup.py:_flush():69] setting env: {}
2021-05-10 14:01:30,985 INFO    MainThread:7276 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-10 14:01:30,986 INFO    MainThread:7276 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'c39ee7c1346fe8a475784b325687e53a46644ee4'}
2021-05-10 14:01:30,986 INFO    MainThread:7276 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\TEC\Documents\GitHub\ML\Proyectos\Proyecto II\wandb\run-20210510_140130-8oyqvmm4\logs\debug.log
2021-05-10 14:01:30,986 INFO    MainThread:7276 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\TEC\Documents\GitHub\ML\Proyectos\Proyecto II\wandb\run-20210510_140130-8oyqvmm4\logs\debug-internal.log
2021-05-10 14:01:30,988 INFO    MainThread:7276 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000162E7785370>
2021-05-10 14:01:30,990 INFO    MainThread:7276 [wandb_init.py:init():369] calling init triggers
2021-05-10 14:01:30,991 INFO    MainThread:7276 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'epochs': 21, 'learningRate': 0.0001, 'batchSize': 32, 'inputSize': 256, 'fc_size_1': 256, 'fc_size_2': 128, 'fc_size_3': 64, 'fc_size_4': 32, 'fc_size_5': 16, 'fc_size_6': 8, 'outputSize': 4, 'classes': ['COVID', 'Lung Opacity', 'Normal', 'Viral Pneumonia'], 'classesLen': 4, 'upSampling': False, 'name': 'WithoutUpsampling_32Batch'}
2021-05-10 14:01:30,991 INFO    MainThread:7276 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 1cmpqh1t
2021-05-10 14:01:30,994 INFO    MainThread:7276 [wandb_run.py:finish():1197] finishing run tecai/MLP/1cmpqh1t
2021-05-10 14:01:30,995 INFO    MainThread:7276 [wandb_run.py:_atexit_cleanup():1524] got exitcode: 0
2021-05-10 14:01:30,996 INFO    MainThread:7276 [wandb_run.py:_restore():1496] restore
2021-05-10 14:01:31,499 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3808
  total_bytes: 3808
}

2021-05-10 14:01:31,840 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3808
  total_bytes: 6828
}

2021-05-10 14:01:32,081 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3808
  total_bytes: 6828
}

2021-05-10 14:01:32,187 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3808
  total_bytes: 6828
}

2021-05-10 14:01:32,298 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3808
  total_bytes: 6828
}

2021-05-10 14:01:32,422 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3808
  total_bytes: 6828
}

2021-05-10 14:01:32,532 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3808
  total_bytes: 6828
}

2021-05-10 14:01:32,644 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3808
  total_bytes: 6828
}

2021-05-10 14:01:32,754 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 3808
  total_bytes: 6828
}

2021-05-10 14:01:32,867 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 6828
  total_bytes: 6828
}

2021-05-10 14:01:32,978 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 6828
  total_bytes: 6828
}

2021-05-10 14:01:33,088 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 6828
  total_bytes: 6828
}

2021-05-10 14:01:33,198 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 6828
  total_bytes: 6828
}

2021-05-10 14:01:33,308 INFO    MainThread:7276 [wandb_run.py:_wait_for_finish():1646] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 6828
  total_bytes: 6828
}

2021-05-10 14:01:34,493 INFO    MainThread:7276 [wandb_run.py:_show_summary():1801] rendering summary
2021-05-10 14:01:34,497 INFO    MainThread:7276 [wandb_run.py:_show_files():1868] logging synced files
2021-05-10 14:01:34,511 INFO    MainThread:7276 [wandb_init.py:init():418] starting backend
2021-05-10 14:01:34,511 INFO    MainThread:7276 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2021-05-10 14:01:34,520 INFO    MainThread:7276 [backend.py:ensure_launched():123] starting backend process...
2021-05-10 14:01:34,801 INFO    MainThread:7276 [backend.py:ensure_launched():127] started backend process with pid: 6952
2021-05-10 14:01:34,802 INFO    MainThread:7276 [wandb_init.py:init():423] backend started and connected
2021-05-10 14:01:34,806 INFO    MainThread:7276 [wandb_init.py:init():465] updated telemetry
2021-05-10 14:01:34,807 INFO    MainThread:7276 [wandb_init.py:init():484] communicating current version
2021-05-10 14:01:37,785 INFO    MainThread:7276 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-10 14:01:37,786 INFO    MainThread:7276 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-10 14:01:38,462 INFO    MainThread:7276 [wandb_init.py:init():522] starting run threads in backend
2021-05-10 14:01:38,695 INFO    MainThread:7276 [wandb_run.py:_console_start():1554] atexit reg
2021-05-10 14:01:38,696 INFO    MainThread:7276 [wandb_run.py:_redirect():1401] redirect: SettingsConsole.WRAP
2021-05-10 14:01:38,696 INFO    MainThread:7276 [wandb_run.py:_redirect():1444] Wrapping output streams.
2021-05-10 14:01:38,696 INFO    MainThread:7276 [wandb_run.py:_redirect():1468] Redirects installed.
2021-05-10 14:01:38,696 INFO    MainThread:7276 [wandb_init.py:init():546] run started, returning control to user process
2021-05-10 14:01:38,697 INFO    MainThread:7276 [wandb_watch.py:watch():39] Watching
2021-05-10 14:01:43,802 INFO    MainThread:7276 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-10 14:01:43,803 INFO    MainThread:7276 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-10 14:01:43,823 INFO    MainThread:7276 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-10 14:01:43,854 INFO    MainThread:7276 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-10 14:01:43,854 INFO    MainThread:7276 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-10 14:02:30,886 INFO    MainThread:7276 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-10 14:02:30,912 INFO    MainThread:7276 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-10 14:02:30,913 INFO    MainThread:7276 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-10 14:02:31,235 INFO    MainThread:7276 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-10 14:02:31,244 INFO    MainThread:7276 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-10 14:02:31,244 INFO    MainThread:7276 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-10 14:02:32,733 INFO    MainThread:7276 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-10 14:02:32,742 INFO    MainThread:7276 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-10 14:02:32,743 INFO    MainThread:7276 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-10 14:02:33,897 INFO    MainThread:7276 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-10 14:02:33,941 INFO    MainThread:7276 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-10 14:02:33,941 INFO    MainThread:7276 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-10 14:02:38,608 INFO    MainThread:7276 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-10 14:02:39,274 INFO    MainThread:7276 [wandb_setup.py:_flush():69] setting env: {}
2021-05-10 14:02:39,274 INFO    MainThread:7276 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-10 14:02:39,274 INFO    MainThread:7276 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'c39ee7c1346fe8a475784b325687e53a46644ee4'}
2021-05-10 14:02:39,275 INFO    MainThread:7276 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\TEC\Documents\GitHub\ML\Proyectos\Proyecto II\wandb\run-20210510_140239-3gsndqwp\logs\debug.log
2021-05-10 14:02:39,275 INFO    MainThread:7276 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\TEC\Documents\GitHub\ML\Proyectos\Proyecto II\wandb\run-20210510_140239-3gsndqwp\logs\debug-internal.log
2021-05-10 14:02:39,277 INFO    MainThread:7276 [wandb_init.py:init():369] calling init triggers
2021-05-10 14:02:39,277 INFO    MainThread:7276 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'epochs': 21, 'learningRate': 0.0001, 'batchSize': 32, 'inputSize': 256, 'fc_size_1': 256, 'fc_size_2': 128, 'fc_size_3': 64, 'fc_size_4': 32, 'fc_size_5': 16, 'fc_size_6': 8, 'outputSize': 4, 'classes': ['COVID', 'Lung Opacity', 'Normal', 'Viral Pneumonia'], 'classesLen': 4, 'upSampling': False, 'name': 'WithoutUpsampling_32Batch'}
2021-05-10 14:02:39,278 INFO    MainThread:7276 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 8oyqvmm4
2021-05-10 14:02:39,281 INFO    MainThread:7276 [wandb_run.py:finish():1197] finishing run tecai/MLP/8oyqvmm4
